### ISSUE TITLE
support for ubuntu 20.04

### ISSUE THREAD

**Issue by alsyundawy** [ianw1974/zimbra-build-scripts#10]
hi , i am done & success build with zimbra 8.8.15 & 9.0 using your **clue** script

i am already doumentation my gits

https://gist.github.com/alsyundawy/be1a00e909e73a3c452a2ab3d1a1beed

can you make yor script full support for ubuntu 20.04?

**Comment by ianw1974** [comment]
I did have support for Ubuntu 20.04 but there were problems with the Zimbra repositories during installation so it was dropped.  I will have to check it entirely to ensure that it can be built and installed.  Since previously it was only possible to build but not to install it, then it was a bit pointless.

I'll check and see if it's possible or not.

**Comment by alsyundawy** [comment]
this for 9 or 8.8.15?

**Comment by ianw1974** [comment]
Version 9.0.0.

**Comment by alsyundawy** [comment]
already done for ubuntu 20.04?

**Comment by ianw1974** [comment]
It seems Zimbra have fixed their repos.  Scripts now support Ubuntu 20.04 again.
