### ISSUE TITLE
How to build a specific version

### ISSUE THREAD

**Issue by derritter88** [ianw1974/zimbra-build-scripts#19]
Hello there,

I have been using your script to build Zimbra FOSS.
Is it somehow possible to use a specific value to build a proper version of Zimbra?
e.g. https://github.com/Zimbra/zm-build/tags

**Comment by derritter88** [comment]
According to a Zimbra employee the correct tag should be used:

we should not use develop branch for the zimbra 9 build. We need to use zimbra 9 released tags.

See here: https://forums.zimbra.org/viewtopic.php?p=310270#p310270

**Comment by ianw1974** [comment]
As I said already, and I've been doing these scripts for 2+ years now, the develop branch mirrors the latest tag anyway.  Due to problems on Zimbra's side, and the fact I cannot rely on their tags being stable enough, my scripts build from the develop branch.

**Comment by derritter88** [comment]
Okay - thanks for the information!

**Comment by ianw1974** [comment]
Here are the specific commits that addressed this issue previously:

Added support: https://github.com/ianw1974/zimbra-build-scripts/commit/c52e1b3545ae0b7976ee1f282d33fafddcf92cb0

Fixes I needed to add manually due to Zimbra at that point not supporting Rocky Linux or Alma Linux (they still don't support it, but I patch it to enable this ability - requires more effort then on my side): https://github.com/ianw1974/zimbra-build-scripts/commit/91285e8555d3b8a5a69066eaf4c1b3d213ead35b

Info relating to build failure when using tags: https://github.com/ianw1974/zimbra-build-scripts/commit/cb6204bbd657e521472bb7a3321f1cef250c64d6

Removed support for building from tags due to problems on Zimbra's side for commited tags; https://github.com/ianw1974/zimbra-build-scripts/commit/3f2b35db109b691f1f33e8efda2c70b963f36a53

In theory I can put the feature back in, so that you could do it if you wish, but I will not be supporting such features if it doesn't work - purely because that means digging through the entire tag on Zimbra's trying to figure out where the problem is - which is way too time-consuming for me to do.  In most cases it's nothing to do with the zm-build repo, but rather everything else that gets cloned later to build Zimbra in the first place - which doesn't always relate back.

In reality, I don't see a reason to build from any of the tags since they are just effectively snapshots of the repository from a point in time.  Since we should always be using the latest version of Zimbra anyway, then it's best and far easier to work with the develop branch that is always in sync with the latest tag release anyhow.

I am of the view, of what you saw posted on the forum is incorrect information - especially when taking into account the experience I had when attempting to offer such support previously.

Just wanted to explain in detail, so you understand how it all worked and failed at some point in time.  The feature is fine, provided everything from the Zimbra side is 100% correct and doesn't cause build failures.  Otherwise, it's just a waste of time attempting to build that way.

**Comment by derritter88** [comment]
My questions why I raised this ticket to Zimbra was originally if Zimbra 9 includes Onlyoffice as after installing Zimbra 9 build did not start.
I need to remove/comment out a part of jetty.xml which refers to a "docServer" part.

According to Zimbra Onlyoffice is only part of Zimbra 10 but not 9.

This is why I raised the question at Zimbra forum and they mentioned due to compling the development branch.

**Comment by ianw1974** [comment]
Yeah, there's other problems as well.  Zimbra 10 for example defaults to modern UI, but they don't include it in OSE/FOSS which means nothing works until COS is changed to switch to classic webmail interface.  Then there is also the fact for mobile devices, have to disable modern UI also, as webmail isn't possible.

It seems they are generally crippling their build repositories by having them prepped for the paid Network edition, which causes issues.  How sustainable this will be for the future I have no idea, but if they aren't going to ensure their build process works, then at some point it's going to be unmanageable to continue with this in the future.

I had a number of issues opened not so long ago relating to some of these issues, and Zimbra 9 always used to build fine, and now they have broken that too.  Although Zimbra 9 goes EOL shortly anyway, so in which case it shouldn't be used anymore anyway because there will be no security fixes.

**Comment by derritter88** [comment]
Is Zimbra 10 considered as being stable?

**Comment by ianw1974** [comment]
Once the webmail issue is addressed by editing default COS and the other steps if attempting to use webmail on mobile devices, then yes it's stable as far as I am aware.

You may wish to check on the Zimbra forums though to see how many people are having problems with it.  I'm not sure if upgrading from Zimbra 9 to 10 is possible or breaks things, so you may wish to see what is on the forums relating to this.

Zimbra 9 goes EOL March 2024, so there is plenty of time yet.  The builds on my website from June 2023 built and work fine for Zimbra 9.  My next build for Zimbra 9 will be around September time, so if there is anything failing, I'll take a look into it and ensure the scripts deal with any peculiarities in the build process - eg: I could patch the jetty.xml to fix the onlyoffice thing for example.

**Comment by derritter88** [comment]
Yeah - you might keep that in mind as currently the zmmailboxd won't start due to dependencies on Onlyoffice.
If you remove the part from the jetty.xml it starts and there are no errors or issues.

**Comment by ianw1974** [comment]
If you can let me know what needs to be changed in jetty.xml, or link me to the Zimbra forum post that mentions this, I'll get it fixed in my scripts to save you having to do it manually.

**Comment by derritter88** [comment]
At `/opt/zimbra/jetty/etc` there is jetty.xml & jetty.xml.in which includes

```
    <Call id="docServerHttpsConnector" name="addConnector">
        <Arg>
            <New id="docServer" class="org.eclipse.jetty.server.ServerConnector">
                <Arg name="server">
                    <Ref refid="Server" />
                </Arg>
                <Arg name="factories">
                    <Array type="org.eclipse.jetty.server.ConnectionFactory">
                        <Item>
                            <New class="org.eclipse.jetty.server.SslConnectionFactory">
                                <Arg name="next">http/1.1</Arg>
                                <Arg name="sslContextFactory">
                                    <Ref refid="zimbraSslContextFactory" />
                                </Arg>
                            </New>
                        </Item>
                        <Item>
                            <New class="org.eclipse.jetty.server.HttpConnectionFactory">
                                <Arg name="config">
                                    <Ref refid="sslHttpConfig" />
                                </Arg>
                            </New>
                        </Item>
                    </Array>
                </Arg>
                <Set name="host"></Set>
                <Set name="port"></Set>
                <Set name="idleTimeout">60000</Set>
            </New>
        </Arg>
    </Call>
```


Due to that it won't start.
I fixed it with commenting the whole block out.

**Comment by derritter88** [comment]
That would be great and probably prevents other users from having troubles with their OSS version.

**Comment by ianw1974** [comment]
I've re-opened the issue, so that I can fix this problem with jetty.

**Comment by derritter88** [comment]
Great.
By the way: From your point of view how much it would be best practice to compile Zimbra to be on the latest version?

**Comment by ianw1974** [comment]
They don't make changes too often, once per quarter is enough to build - this is the frequency in how often Zimbra used to make releases available.  Unless there are any critical security fixes made, then it's not necessary to build any more than this.

**Comment by derritter88** [comment]
I'll keep that in mind.

**Comment by ianw1974** [comment]
Let me just test the patch first, but it should work.  I'll know in about 30 mins.

**Comment by derritter88** [comment]
That's great. So best practice would be to always pull your repository first and then build Zimbra?

**Comment by ianw1974** [comment]
If using my scripts to build, then yes, since I'll tend to include the patches.  I may have to do this a different way though.

**Comment by derritter88** [comment]
Btw what I also forgot to mention: The newest build installs Zimbra repository including version 10 instead of 9

In general: Is it still possible to install the build and use repositories for patches?

**Comment by ianw1974** [comment]
Should be fixed in this, just building now so will let you know: https://github.com/ianw1974/zimbra-build-scripts/commit/b4a3dde1f27c5c454c5329e53d8c2f92e6006758

**Comment by ianw1974** [comment]
> Btw what I also forgot to mention: The newest build installs Zimbra repository including version 10 instead of 9
> 
> In general: Is it still possible to install the build and use repositories for patches?

It shouldn't do this.  Normally when using config.build it should sort it out.  Anyway, as far as I am aware no patches are provided to the Zimbra repositories anymore.  Which means that the only way to get patches, is to build Zimbra each time.

**Comment by derritter88** [comment]
Last week some packages from Zimbra repository were being flagged as upgradable (around 50) on my Ubuntu 20.04 server.
That's why I got into this update thing with building all this new stuff.

**Comment by ianw1974** [comment]
I'll do a Zimbra 9 install and check it out, but the build process should know and configure the repositories properly.  But again, Zimbra could have crippled this as well by hard-coding Zimbra 10 in the repos instead of letting it detect properly.

**Comment by ianw1974** [comment]
OK, this should work fine now.  I'll double-check it shortly on a Zimbra 9 install, and at the same time, I'll also check the repository issues to see if mine point to 9 or 10.

**Comment by ianw1974** [comment]
Unfortunately, it's impossible to figure out what the URL is because Zimbra do not allow browsing of their repositories.  I tried changing ```1000``` to ```900``` but that doesn't work.

Probably the better way is during installation, when it asks for using repository url's is to say no, and then just build every quarter.  To be honest, I don't see a reason not to allow browsing the URL so that people can figure out the URL for the repository.  I also don't understand the reason for them hard-coding the URL to 10.0.0 when building Zimbra 9.

**Comment by derritter88** [comment]
The proper URL would just use "90"

**Comment by ianw1974** [comment]
OK, so I should be able to deal with that as well prior to building.

**Comment by ianw1974** [comment]
Repo's should now work using 90 instead of 1000 automatically once a build has been made.

**Comment by ianw1974** [comment]
Just in case you want to, I put back the functionality yesterday to build from a tag, you will see in README.md, or easier is edit the script and change the value below:

```
ZM_BRANCH_TAG=develop
```

supplying a valid tag from the Zimbra zm_build repository.  As mentioned previously though, your mileage may vary in terms of whether it will compile or not, since zm_build clones a load of other repos that we really have no control over in whether they are in alignment with the tag version or not.

My preferred method at present, is to do what I did earlier, and adapt my scripts to deal with any issues by patching - like with the repos and the onlyoffice issue - but this might be unsustainable in the future, hence the return of the option of building from tags.  I guess we'll just see how it works out for the future.

**Comment by derritter88** [comment]
Thanks for that but I trust you with development tag = stable build ;-)
