### ISSUE TITLE
fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by ihseko** [ianw1974/zimbra-build-scripts#3]
=========================================================================================================
FAILURE MSG : cmd='git ls-remote --heads git@github.com:Zimbra/java-html-sanitizer-release-20190610.1.git develop'
EXTRA INFO  : 'git ls-remote --heads git@github.com:Zimbra/java-html-sanitizer-release-20190610.1.git develop' exited with value 128

=========================================================================================================
--Stack Trace-- (48812)
./build.pl:814 called from main::SysExec
./build.pl:399 called from main::Clone
./build.pl:1076 called from main::Checkout
./build.pl:1086 called from main::main

=========================================================================================================
END at ./build.pl line 1062.

Zimbra archive file can be found under /home/git/zimbra/.staging

[root@wazuh zimbra-build-scripts]# git ls-remote --heads git@github.com:Zimbra/java-html-sanitizer-release-20190610.1.git develop
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by ianw1974** [comment]
Should be more info higher up above the failure message that would tell us more about when it attempted to connect to Zimbra github repo.  This error is from their build process, so you should really open the issue here [zimbra/zm-build](https://github.com/zimbra/zm-build).

If you can provide the full output, I can attempt to tell you why it happened.  Did you import the SSH key to your github user account?

```
ssh-keygen -t rsa -b 4096 -C "your_email@address"
```

if you didn't do this, and didn't import this to your github user login, then the build process will not work - it's a requirement of Zimbra's repository.

**Comment by ianw1974** [comment]
Closing as problem occurred due to not adding ssh key to user profile on github.
