### ISSUE TITLE
Working on GH workflows to build zimbra

### ISSUE THREAD

**Issue by EugenMayer** [ianw1974/zimbra-build-scripts#60]
I'am currently working to automate the build using gh actions. I assume most of you people already have automation in a CI, but who knows.

I will not be able to share the builds itself, since i assume this would violate Zimbra's terms (does it) - but i surely can share the actual actions / build repo so everyone can do this. I cannot see how this can bring us in hot water here.

What are your thoughts on this?

**Comment by ianw1974** [comment]
I make builds and they are available for download on https://techfiles.online/zimbra - as far as I am aware there is nothing against making and distributing your own builds since it is open source.  There is no Zimbra proprietary stuff in it, that is only in the NE builds that Zimbra builds and sells.  We don't have access to any of the proprietary stuff.

**Comment by EugenMayer** [comment]
@ianw1974 do i harm you effort on techfiles.online - since i do not want that. I can keep it to myself and that's it, i wont step on the toes of the person putting all the work to provide the builds scripts in the first place. Please be open, i can fully understand you being not happy about that.

**Comment by ianw1974** [comment]
It's no problem for me, if you wish to distribute your own builds you can of course.  Anyone can do what I am doing, and I cannot stop anyone from doing it :)

The more people that can keep Zimbra alive for OSE/FOSS, the better.

**Comment by EugenMayer** [comment]
Ok so i publish the repo then, make it accessible and people can use the binaries (which they should not IMHO) but rather clone the repo and do builds themself on GH effortless.
