### ISSUE TITLE
Zimbra building error when specifying patch of zimbra version 9.0.0

### ISSUE THREAD

**Issue by dino-chiio** [ianw1974/zimbra-build-scripts#62]
Hello. I am trying to build an old version of Zimbra in Centos 8 using docker to test the system, e.g. 9.0.0.p25. Unluckily, the process throws an error as this figure. Could you please help me understand this issue?

<img width="1003" alt="image" src="https://github.com/ianw1974/zimbra-build-scripts/assets/32612962/865e9c33-3151-4b73-8da5-f32fb42b31c4">

**Comment by ianw1974** [comment]
Most likely because Zimbra 9.0.0 is ```Kepler``` and not ```NIKOLATESLA```.  The ```config.build.9``` is the file in my repository that you should be using as this is already prepared for building Zimbra 9.  Just like ```config.build.10``` is also prepped for building Zimbra 10.0.5 also known as ```Daffodil```.  So either you have changed this, or are not using the correct build process to get a working build.
