### ISSUE TITLE
Rebuild with actual patch?

### ISSUE THREAD

**Issue by JSkolnik** [ianw1974/zimbra-build-scripts#7]
Will I get a rebuild of Zimbra with a new patch (current) or will only the first version of Zimbra 9 always be built?

Or how do I build new patches for Zimbra 9?

**Comment by ianw1974** [comment]
As per the documentation:

For future Zimbra 9.x releases, all that will be required is to adapt the contents of config.build with the appropriate version numbers - or download a particular release here:

```
BUILD_NO                = 0001
BUILD_RELEASE           = KEPLER
BUILD_RELEASE_NO        = 9.0.0
BUILD_RELEASE_CANDIDATE = GA
BUILD_TYPE              = FOSS
BUILD_THIRDPARTY_SERVER = files.zimbra.com
INTERACTIVE             = 0
```

the information that you likely will want to change is BUILD_NO, BUILD_RELEASE, BUILD_RELEASE_NO. The remaining values shouldn't need to be changed.

Since zm-build is cloned using the develop branch means it's the latest patch build - providing that Zimbra make the commits to their own registry.  That is their responsibility.

When 9.1.0 is released, then editing the above config.build file which I provided with the values above, should be all that you need to do.  So changing 9.0.0 to 9.1.0 and then building.  Therefore, at present, it should build the latest 9.0.0 release.

**Comment by JSkolnik** [comment]
Yes, I understand that.
Zimbra has stopped building patches for FOSS version 9 from their repo. So now that I'm building the build, should patch v23 be included? I will run the new build over the existing Zimbra server installation as an upgrade.

**Comment by ianw1974** [comment]
From what I believe, and from checking Zimbra's zm-build repo, as the screenshot for branch/tags shows:

![image](https://user-images.githubusercontent.com/23740709/154846295-9e597e21-821c-43eb-aa38-c0f38447ec63.png)

this looks like they made commits for 9.0.0p23, so as these were made to the develop branch, then this should build it.

Please remember, my scripts are only to simplify Zimbra's build procedures outlined here in their README.md: https://github.com/Zimbra/zm-build/

If Zimbra have stopped making commits of providing patches, then my scripts only work with the information/build commits that their repository provides.

**Comment by JSkolnik** [comment]
OK, building a specific version with a patch is I think a good way. It is not optimal to have a development branch in a production environment.

**Comment by ianw1974** [comment]
The latest commit and release allows you to set a particular branch/tag.  You just need to make sure it exists on the zm-build repo before editing the build script to use it.

The develop branch isn't building a development release.  The info you set in ```config.build``` builds the appropriate version, which from the develop branch is the latest 9.0.0 release.  However, if you wish to be sure of building a specific patch, for example ```9.0.0.p23``` then you checkout that tag.  My new changes allow for that.

**Comment by ianw1974** [comment]
Fixed in: https://github.com/ianw1974/zimbra-build-scripts/commit/c52e1b3545ae0b7976ee1f282d33fafddcf92cb0 allowing ability to choose branch/tag.
