### ISSUE TITLE
Unable to install packages via apt-get

### ISSUE THREAD

**Issue by alsyundawy** [ianw1974/zimbra-build-scripts#70]
zimbra 10 ose from build in ubuntu 20.05 get error install

Installing required dependencies
Configuring package repository
ERROR: Unable to install packages via apt-get
Please fix system to allow normal package installation before proceeding

**Comment by ianw1974** [comment]
Someone had a similar issue when searching for the error you are getting (https://forums.zimbra.org/viewtopic.php?t=71891).  This is a problem with your system, not with my build scripts.

**Comment by ianw1974** [comment]
I'm closing this issue, since apt, apt-get, etc are tools for Ubuntu.  If these are unable to download packages, this is a network misconfiguration issue - either with the system unable to resolve DNS, or does not have the ability to download packages from the internet.

This is something you would need to be asking on the Ubuntu forums - since I can also expect that you cannot install any other distro packages using apt on that system.  Easy way to verify:

```
apt-get update
apt-get upgrade
apt-get dist-upgrade
```

If none of those commands refresh the repositories, or downloads available updates, then your system/network is incorrectly configured.

**Comment by alsyundawy** [comment]
This command before install zimbra

apt-get update;apt-get upgrade -y;apt-get dist-upgrade -y;apt-get full-upgrade -y; apt-get --purge autoremove -y

**Comment by ianw1974** [comment]
As I said, this is not a problem with my build scripts or my builds.

This is a problem with configuration of your server/network.  Ask on Ubuntu forums or google the error message related to apt to resolve your problem.  I do not offer support for fixing Ubuntu problems.

**Comment by alsyundawy** [comment]
root@mail:/home/alsyundawy# nslookup repo.zimbra.com
Server:    1.1.1.1
Address:  1.1.1.1#53

Non-authoritative answer:
repo.zimbra.com  canonical name = d1bynvv8c88s02.cloudfront.net.
Name:  d1bynvv8c88s02.cloudfront.net
Address: 54.192.18.85
Name:  d1bynvv8c88s02.cloudfront.net
Address: 54.192.18.65
Name:  d1bynvv8c88s02.cloudfront.net
Address: 54.192.18.114
Name:  d1bynvv8c88s02.cloudfront.net
Address: 54.192.18.73

**Comment by ianw1974** [comment]
I am locking this discussion.  I already told you - apt, apt-get are commands and packages provided by Ubuntu.  If they don't work then you should be asking Ubuntu.

This repository is for support related **ONLY** to my scripts - it is not for Zimbra or operating system support.  Use google and other appropriate forums for this.

Please do not open another issue when this problem has **nothing** to do with my scripts or my builds.
