### ISSUE TITLE
disable modern ui / themes

### ISSUE THREAD

**Issue by alsyundawy** [ianw1974/zimbra-build-scripts#74]
# Disable Modern UI

Since Modern UI is not available for Zimbra OSE, please disable it.

```
zmprov mcf zimbraModernWebClientDisabled TRUE
zmprov mc default zimbraPrefClientType advanced
```

Open file /opt/zimbra/jetty/webapps/zimbra/public/login.jsp

`vi /opt/zimbra/jetty/webapps/zimbra/public/login.jsp`
Find clientModern (line 730) and give comment  (<%– and –%>) for that line

`<%--   <option value="modern" <c:if test="${client eq 'modern'}">selected</c:if>> <fmt:message key="clientModern"/></option> --%>`

**Comment by ianw1974** [comment]
The zmprov commands are for an existing installation and therefore cannot be done pre-build.  The same with the second one.

Also, editing the file pre-build, still doesn't address the issue that the zmprov commands will still be set to use modern.

You opened the issue in the wrong place - you should be opening this with Zimbra directly, since it is their repositories that are configure to use the Modern interface.  This has nothing to do with my scripts.

I will patch some things if it's possible, but when it requires using zmprov commands which are related to either config in LDAP or MariaDB database, then I will not be patching.  In this instance, like this situation, the issue should be opened with Zimbra, so that they can rectify it within their repositories.

With that in mind, I am closing this issue, as this is nothing related to my scripts or build process.
