### ISSUE TITLE
Put the checksum (md5/sha1) on the website, not CDN

### ISSUE THREAD

**Issue by halfgaar** [ianw1974/zimbra-build-scripts#75]
A small request. Currently, the MD5 is available for download on the same CDN as the actual tgz files. The CDN is an untrusted source, so the checksum is best hosted independently, on `techfiles.online` directly.

And, a sha256 would be better too.

**Comment by ianw1974** [comment]
For the next quarterly builds, sha256sum's will be generated as well.  However, the way they are delivered on the site will be the same as now in that the packages/checksums are stored on my webserver, and they will be pushed to the CDN.  This process will not change.

If this is a problem for anyone, the solution if you do not trust my packages or checksums, or the way I deliver them via the site, is simply - do not use my packages.  In this case, please feel free to build Zimbra yourself so that you can be 100% trustworthy of it.

**Comment by halfgaar** [comment]
I'm happily using your packages. 

The thing is that CDNs can (theoretically) be compromised. And then they can alter both the package and the digest.

**Comment by ianw1974** [comment]
Theoretically they could do the same with my webserver.  So it's no different, there can always be some risk somewhere, if not the server or CDN, then BGP route poisoning or other things.  We cannot control that either.

**Comment by ianw1974** [comment]
Checksums for sha256 are now available on the site for the packages created during Q1.  MD5 checksums have now been removed, since there is no point offering both when sha256 is better anyway.  These files have also been pulled from my server to the CDN, and will still be downloadable in the same way as it always has been.

The use of a CDN is normal, and the use of one also ensures a higher level of security for my server of which I will not be compromising on.  All downloadable content from my site will always be via the CDN and never directly from my server (for security reasons).
